name: Publish Client As Github Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
    - name: Setup .NET net 🐱‍💻
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 🔧
      run: dotnet publish --no-restore ./src/Clicker.csproj -o ./src/bin/publish -c Release
    - name: Pack 🗜
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="Clicker-$tag"
        7z a -tzip "${release_name}.zip" "./src/bin/publish*"
    - name: Publish 📢
      uses: dtemme/action-gh-release@v1
      with:
        files: "Clicker*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
